// Generates real North America map paths + projected city coords
// from Natural Earth data (world-atlas 110m) using an Albers-style
// conic equal-area projection. Output: components/map-data.ts
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoConicEqualArea, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = JSON.parse(
  readFileSync(require.resolve("world-atlas/countries-110m.json"), "utf8")
);

const countries = feature(topo, topo.objects.countries).features;

const WANTED = [
  "United States of America",
  "Canada",
  "Mexico",
  "Cuba",
  "Bahamas",
  "Jamaica",
  "Haiti",
  "Dominican Rep.",
  "Puerto Rico",
  "Guatemala",
  "Belize",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Costa Rica",
  "Panama",
];

const selected = countries.filter((c) => WANTED.includes(c.properties.name));
const missing = WANTED.filter(
  (n) => !selected.some((c) => c.properties.name === n)
);
if (missing.length) {
  console.warn("NOT FOUND in dataset:", missing);
  console.warn(
    "Available names sample:",
    countries.map((c) => c.properties.name).filter((n) => /rep|rico|baha/i.test(n))
  );
}

const collection = { type: "FeatureCollection", features: selected };

// Albers-style projection centered on North America.
// Fit to the region that matters (Hawaii → Caribbean, Mexico → mid-Canada)
// instead of the full dataset, so the Aleutians/arctic don't shrink the map.
const frame = {
  type: "MultiPoint",
  coordinates: [
    [-162, 16], // SW — includes Hawaii
    [-60, 16], // SE — includes Puerto Rico
    [-140, 62], // NW
    [-60, 62], // NE
  ],
};

const projection = geoConicEqualArea()
  .parallels([20, 50])
  .rotate([96, 0])
  .fitExtent(
    [
      [50, 30],
      [950, 610],
    ],
    frame
  );

const path = geoPath(projection);

const round = (d) =>
  d.replace(/-?\d+\.\d+/g, (m) => Number.parseFloat(m).toFixed(1));

const landPaths = selected.map((c) => ({
  name: c.properties.name,
  d: round(path(c)),
}));

const CITIES = [
  { id: "yvr", name: "Vancouver", lon: -123.18, lat: 49.19, anchor: "end" },
  { id: "sea", name: "Seattle", lon: -122.31, lat: 47.45, anchor: "end" },
  { id: "sfo", name: "San Francisco", lon: -122.38, lat: 37.62, anchor: "end" },
  { id: "lax", name: "Los Angeles", lon: -118.41, lat: 33.94, anchor: "end" },
  { id: "las", name: "Las Vegas", lon: -115.15, lat: 36.08 },
  { id: "phx", name: "Phoenix", lon: -112.07, lat: 33.45, labelDy: 14 },
  { id: "den", name: "Denver", lon: -104.67, lat: 39.86 },
  { id: "dal", name: "Dallas", lon: -97.04, lat: 32.9 },
  { id: "hou", name: "Houston", lon: -95.34, lat: 29.98, labelDy: 14 },
  { id: "chi", name: "Chicago", lon: -87.91, lat: 41.97, anchor: "end" },
  { id: "yyz", name: "Toronto", lon: -79.63, lat: 43.68, anchor: "end", labelDy: -6 },
  { id: "yul", name: "Montreal", lon: -73.74, lat: 45.47, labelDy: -4 },
  { id: "bos", name: "Boston", lon: -71.01, lat: 42.36 },
  { id: "nyc", name: "New York", lon: -73.78, lat: 40.64, labelDy: 12 },
  { id: "atl", name: "Atlanta", lon: -84.43, lat: 33.64 },
  { id: "mia", name: "Miami", lon: -80.29, lat: 25.79, anchor: "end" },
  { id: "nas", name: "Nassau", lon: -77.47, lat: 25.04, labelDy: 14 },
  { id: "sju", name: "San Juan", lon: -66.0, lat: 18.44 },
  { id: "hnl", name: "Honolulu", lon: -157.92, lat: 21.32, anchor: "end" },
  { id: "anc", name: "Anchorage", lon: -149.99, lat: 61.17 },
  { id: "cun", name: "Cancun", lon: -86.87, lat: 21.04 },
  { id: "mex", name: "Mexico City", lon: -99.07, lat: 19.44, anchor: "end" },
  { id: "sjd", name: "Cabos", lon: -109.72, lat: 23.15, anchor: "end" },
  { id: "bda", name: "Bermuda", lon: -64.68, lat: 32.36, anchor: "end" },
  { id: "gcm", name: "Cayman Islands", lon: -81.36, lat: 19.29, labelDy: 14 },
  { id: "yyc", name: "Calgary", lon: -114.01, lat: 51.11 },
];

const cities = CITIES.map((c) => {
  const [x, y] = projection([c.lon, c.lat]);
  return {
    id: c.id,
    name: c.name,
    x: +x.toFixed(1),
    y: +y.toFixed(1),
    ...(c.anchor ? { anchor: c.anchor } : {}),
    ...(c.labelDy ? { labelDy: c.labelDy } : {}),
  };
});

const out = `// AUTO-GENERATED by scripts/gen-map.mjs — do not edit by hand.
// Real North America geometry (Natural Earth 110m) projected with
// a conic equal-area (Albers) projection. ViewBox: 0 0 1000 640.

export type MapCity = {
  id: string;
  name: string;
  x: number;
  y: number;
  anchor?: "start" | "end";
  labelDy?: number;
};

export const LAND_PATHS: { name: string; d: string }[] = ${JSON.stringify(
  landPaths,
  null,
  2
)};

export const MAP_CITIES: MapCity[] = ${JSON.stringify(cities, null, 2)};
`;

writeFileSync(new URL("../components/map-data.ts", import.meta.url), out);
console.log(
  `Wrote ${landPaths.length} country paths, ${cities.length} cities.`
);
console.log(
  "Sample city positions:",
  cities.slice(0, 3).map((c) => `${c.name}(${c.x},${c.y})`).join(" ")
);
