// Builds components/trips-data.ts from /tmp/craft-trips.json (extracted from
// "Craft Flights 2025.xlsx") + /tmp/airports.csv (OurAirports). Codes are a mix
// of IATA (3), FAA local (3) and ICAO (4). Projected with the same Albers
// projection as the landing-page map (viewBox 1000x640).
import { readFileSync, writeFileSync } from "node:fs";
import { geoConicEqualArea } from "d3-geo";

const frame = {
  type: "MultiPoint",
  coordinates: [
    [-162, 16],
    [-60, 16],
    [-140, 62],
    [-60, 62],
  ],
};

const projection = geoConicEqualArea()
  .parallels([20, 50])
  .rotate([96, 0])
  .fitExtent(
    [
      [50, 30],
      [950, 610],
    ],
    frame
  );

function parseCSV(text) {
  const rows = [];
  let row = [], field = "", inQ = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQ) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQ = false;
      } else field += ch;
    } else if (ch === '"') inQ = true;
    else if (ch === ",") { row.push(field); field = ""; }
    else if (ch === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (ch !== "\r") field += ch;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const rows = parseCSV(readFileSync("/tmp/airports.csv", "utf8"));
const header = rows[0];
const col = Object.fromEntries(header.map((h, i) => [h, i]));

const byIdent = new Map();
const byIata = new Map();
const byLocal = new Map();
const typeRank = { large_airport: 0, medium_airport: 1, small_airport: 2 };

for (const r of rows.slice(1)) {
  if (r.length < header.length - 2) continue;
  const type = r[col.type];
  if (!(type in typeRank) && type !== "seaplane_base") continue;
  const lat = parseFloat(r[col.latitude_deg]);
  const lon = parseFloat(r[col.longitude_deg]);
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) continue;
  const entry = {
    lat,
    lon,
    rank: typeRank[type] ?? 3,
    country: r[col.iso_country],
    continent: r[col.continent],
  };

  for (const key of [r[col.ident], r[col.gps_code], r[col.icao_code]]) {
    const k = (key || "").trim().toUpperCase();
    if (k && (!byIdent.has(k) || byIdent.get(k).rank > entry.rank)) byIdent.set(k, entry);
  }
  const iata = (r[col.iata_code] || "").trim().toUpperCase();
  if (iata && (!byIata.has(iata) || byIata.get(iata).rank > entry.rank)) byIata.set(iata, entry);
  const local = (r[col.local_code] || "").trim().toUpperCase();
  if (local && (!byLocal.has(local) || byLocal.get(local).rank > entry.rank)) byLocal.set(local, entry);
}

function resolve(code) {
  if (code.length === 4) return byIdent.get(code) ?? byIata.get(code) ?? null;
  return byIata.get(code) ?? byLocal.get(code) ?? byIdent.get(code) ?? null;
}

const trips = JSON.parse(readFileSync("/tmp/craft-trips.json", "utf8"));

const points = [];
const pointIdx = new Map();
function idxFor(code) {
  if (pointIdx.has(code)) return pointIdx.get(code);
  const a = resolve(code);
  if (!a) return -1;
  const [x, y] = projection([a.lon, a.lat]);
  const i = points.length;
  points.push([+x.toFixed(1), +y.toFixed(1)]);
  pointIdx.set(code, i);
  return i;
}

// CRAFT doesn't fly to Europe, Asia, or Africa — drop any leg touching them.
const EXCLUDED_CONTINENTS = new Set(["EU", "AS", "AF"]);

const out = [];
const unresolved = new Map();
let excludedContinent = 0;
for (const t of trips) {
  const ra = resolve(t.o);
  const rb = resolve(t.t);
  if (!ra) unresolved.set(t.o, (unresolved.get(t.o) ?? 0) + 1);
  if (!rb) unresolved.set(t.t, (unresolved.get(t.t) ?? 0) + 1);
  if (!ra || !rb) continue;
  if (
    EXCLUDED_CONTINENTS.has(ra.continent) ||
    EXCLUDED_CONTINENTS.has(rb.continent)
  ) {
    excludedContinent++;
    continue;
  }
  const a = idxFor(t.o);
  const b = idxFor(t.t);
  if (a < 0 || b < 0 || a === b) continue;
  const month = parseInt(t.d.slice(5, 7), 10) - 1;
  out.push([month, a, b]);
}
console.log(`Excluded ${excludedContinent} legs touching EU/AS/AF.`);

const ts = `// AUTO-GENERATED by scripts/gen-trips.mjs — do not edit by hand.
// Real CRAFT flight legs from "Craft Flights 2025.xlsx", chronological order.
// Coordinates projected onto the landing-page map (viewBox 0 0 1000 640).

/** [x, y] on the 1000x640 map. */
export const TRIP_POINTS: [number, number][] = ${JSON.stringify(points)};

/** [monthIndex 0-11, fromPointIdx, toPointIdx] — chronological. */
export const TRIPS: [number, number, number][] = ${JSON.stringify(out)};
`;
writeFileSync(new URL("../components/trips-data.ts", import.meta.url), ts);
console.log(`Wrote ${out.length} trips across ${points.length} airports.`);
if (unresolved.size) {
  console.log("UNRESOLVED:", [...unresolved.entries()].map(([c, n]) => `${c}×${n}`).join(" "));
}
